### ISSUE TITLE
Can not find "Defines.hpp"!

### ISSUE THREAD

**Issue by Minotaur-CN** [srinath1905/kaadugal#1]
Dear srinath,
Thanks for your sharing code on kaadugal, I can not find Defines.hpp in your repo, could you update your github？

Regards!

Rui

**Comment by drsrinathsridhar** [comment]
Thanks for opening an issue for this.

Defines.hpp has been renamed to KaadugalDefines.hpp.
Where are you trying to include Defines.hpp?

It's possible I forgot to rename "Defines.hpp" in one of the examples.

**Comment by drsrinathsridhar** [comment]
Fyi, this issue has been fixed.
